services:
  postgres:
    image: postgres:17

    container_name: carjim-postgres

    restart: always

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: C@rj1mL@bs$2026$
      POSTGRES_DB: carjim_labs

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: